/**
 * More curated places (second batch), so the guide and the trip planner have enough choice in each
 * destination. Coordinates, hours and visit lengths are approximate and must be reviewed by the
 * operations team before launch (they can be edited from the back office).
 */
import type { OpeningSlot, Place } from "./types";

const daily = (open: string, close: string): OpeningSlot[] => [{ days: [0, 1, 2, 3, 4, 5, 6], open, close }];
/** Closed on Friday morning (open after the Friday prayer). */
const friAfternoon = (open: string, close: string, friOpen = "16:00"): OpeningSlot[] => [
  { days: [0, 1, 2, 3, 4, 6], open, close },
  { days: [5], open: friOpen, close },
];
type Seed = Omit<Place, "id" | "source" | "status" | "updatedAt" | "tags"> & { tags?: Place["tags"] };

export const EXTRA_SEED: Seed[] = [
  // ---------------------------------------------------------------- Riyadh
  { city: "RUH", category: "nature", nameAr: "وادي حنيفة", nameEn: "Wadi Hanifah", descriptionAr: "وادٍ أُعيد تأهيله بممرات مشي وبحيرات ومساحات خضراء على امتداد الرياض.", descriptionEn: "Restored valley with walking trails, lakes and green spaces running through Riyadh.", lat: 24.6955, lng: 46.5905, open24h: true, durationMins: 120, tags: ["family", "kids", "free", "outdoor"] },
  { city: "RUH", category: "heritage", nameAr: "مركز الملك عبدالعزيز التاريخي — قصر المربع", nameEn: "King Abdulaziz Historical Center — Murabba Palace", descriptionAr: "قصر الملك عبدالعزيز الطيني وحدائق ومتاحف تروي تاريخ توحيد المملكة.", descriptionEn: "King Abdulaziz's mud-brick palace with gardens and museums on the Kingdom's unification.", lat: 24.6479, lng: 46.7106, hours: friAfternoon("08:00", "20:00"), durationMins: 90, tags: ["family", "indoor", "free"] },
  { city: "RUH", category: "shopping", nameAr: "سوق الزل", nameEn: "Souq Al Zal", descriptionAr: "من أقدم أسواق الرياض للسجاد والبشوت والعطور والتحف.", descriptionEn: "One of Riyadh's oldest souqs for carpets, bishts, perfumes and antiques.", lat: 24.6305, lng: 46.7155, hours: friAfternoon("09:00", "23:00"), durationMins: 75, tags: ["family", "outdoor"] },
  { city: "RUH", category: "mosque", nameAr: "جامع الإمام تركي بن عبدالله", nameEn: "Imam Turki bin Abdullah Grand Mosque", descriptionAr: "الجامع الكبير في قلب الرياض التاريخي بجوار قصر الحكم.", descriptionEn: "The grand mosque at the historic heart of Riyadh, next to Qasr Al Hukm.", lat: 24.6318, lng: 46.7128, open24h: true, durationMins: 30, tags: ["free", "womenSection", "wheelchair"] },
  { city: "RUH", category: "landmark", nameAr: "برج الفيصلية — الكرة", nameEn: "Al Faisaliah Tower — The Globe", descriptionAr: "برج شهير بكرة زجاجية في قمته تطل على الرياض.", descriptionEn: "Landmark tower with a glass globe at the top overlooking Riyadh.", lat: 24.6905, lng: 46.6853, hours: daily("10:00", "23:00"), durationMins: 45, tags: ["family", "indoor", "wheelchair"] },
  { city: "RUH", category: "landmark", nameAr: "مركز الملك عبدالله المالي", nameEn: "King Abdullah Financial District", descriptionAr: "حي حديث بأبراج لافتة وممرات مشي معلّقة ومقاهٍ ومطاعم.", descriptionEn: "Modern district of striking towers, sky-walks, cafés and restaurants.", lat: 24.7645, lng: 46.642, open24h: true, durationMins: 75, tags: ["family", "outdoor", "wheelchair", "free"] },
  { city: "RUH", category: "shopping", nameAr: "الرياض بارك", nameEn: "Riyadh Park Mall", descriptionAr: "مركز تسوق كبير بعلامات عالمية وسينما ومطاعم.", descriptionEn: "Large mall with international brands, a cinema and restaurants.", lat: 24.7535, lng: 46.6297, hours: daily("10:00", "00:00"), durationMins: 120, tags: ["family", "kids", "indoor", "wheelchair"] },
  { city: "RUH", category: "shopping", nameAr: "فيا رياض", nameEn: "Via Riyadh", descriptionAr: "وجهة فاخرة للتسوق والمطاعم والسينما بطراز معماري نجدي.", descriptionEn: "Upscale shopping, dining and cinema destination in Najdi-inspired architecture.", lat: 24.6823, lng: 46.6208, hours: daily("12:00", "00:00"), durationMins: 120, tags: ["family", "outdoor", "wheelchair"] },
  { city: "RUH", category: "park", nameAr: "حديقة الملك عبدالله بالملز", nameEn: "King Abdullah Park (Al Malaz)", descriptionAr: "حديقة واسعة ببحيرة ونافورة راقصة وملاعب للأطفال.", descriptionEn: "Large park with a lake, a dancing fountain and playgrounds.", lat: 24.6655, lng: 46.7375, hours: daily("16:00", "00:00"), durationMins: 90, tags: ["family", "kids", "outdoor"] },
  { city: "RUH", category: "park", nameAr: "منتزه السلام", nameEn: "Salam Park", descriptionAr: "حديقة تاريخية ببحيرة ونخيل ومسارات مشي في وسط الرياض.", descriptionEn: "Historic park with a lake, palms and walking paths in central Riyadh.", lat: 24.6242, lng: 46.7031, hours: daily("16:00", "00:00"), durationMins: 75, tags: ["family", "kids", "outdoor", "free"] },
  { city: "RUH", category: "entertainment", nameAr: "حديقة حيوان الرياض", nameEn: "Riyadh Zoo", descriptionAr: "حديقة حيوان عائلية بأقسام للحيوانات من قارات مختلفة.", descriptionEn: "Family zoo with animals from different continents.", lat: 24.6707, lng: 46.731, hours: daily("16:00", "23:00"), durationMins: 120, tags: ["family", "kids", "outdoor"] },
  { city: "RUH", category: "entertainment", nameAr: "بوليفارد وورلد", nameEn: "Boulevard World", descriptionAr: "منطقة ترفيهية بأجنحة تحاكي ثقافات العالم وعروض وألعاب (في موسم الرياض).", descriptionEn: "Entertainment zone with areas themed on world cultures, shows and rides (Riyadh Season).", lat: 24.7722, lng: 46.5938, hours: daily("16:00", "02:00"), durationMins: 180, tags: ["family", "kids", "nightlife", "outdoor"] },
  { city: "RUH", category: "nature", nameAr: "الرمال الحمراء", nameEn: "Red Sand Dunes", descriptionAr: "كثبان رملية حمراء غرب الرياض للتطعيس والتزلج على الرمال والغروب.", descriptionEn: "Red dunes west of Riyadh for dune bashing, sandboarding and sunsets.", lat: 24.5405, lng: 46.2005, open24h: true, durationMins: 180, tags: ["outdoor", "free"] },
  { city: "RUH", category: "park", nameAr: "ممشى الحي الدبلوماسي", nameEn: "Diplomatic Quarter Trails", descriptionAr: "مسارات مشي وحدائق هادئة على حافة وادي حنيفة.", descriptionEn: "Quiet walking trails and gardens on the edge of Wadi Hanifah.", lat: 24.683, lng: 46.623, open24h: true, durationMins: 75, tags: ["family", "outdoor", "free", "wheelchair"] },
  { city: "RUH", category: "restaurant", nameAr: "قرية نجد", nameEn: "Najd Village", descriptionAr: "مطعم بأجواء بيت نجدي تقليدي يقدم الكبسة والجريش والمرقوق.", descriptionEn: "Restaurant in a traditional Najdi house setting serving kabsa, jareesh and marqooq.", lat: 24.704, lng: 46.669, hours: daily("12:00", "00:00"), priceLevel: 2, cuisineAr: "سعودي", cuisineEn: "Saudi", durationMins: 90, tags: ["family", "womenSection"] },
  { city: "RUH", category: "cafe", nameAr: "مقاهي حي الطريف — الدرعية", nameEn: "Diriyah Cafés", descriptionAr: "مقاهٍ بإطلالة على الدرعية للقهوة السعودية والتمور مساءً.", descriptionEn: "Cafés overlooking Diriyah for Saudi coffee and dates in the evening.", lat: 24.7342, lng: 46.5782, hours: daily("16:00", "01:00"), priceLevel: 2, cuisineAr: "قهوة", cuisineEn: "Coffee", durationMins: 60, tags: ["family", "outdoor"] },

  // ---------------------------------------------------------------- Jeddah
  { city: "JED", category: "beach", nameAr: "الواجهة البحرية بجدة", nameEn: "Jeddah Waterfront", descriptionAr: "ممشى بحري حديث بشواطئ ومرافق وألعاب مائية للعائلات.", descriptionEn: "Modern seafront promenade with beaches, facilities and water play for families.", lat: 21.6045, lng: 39.105, open24h: true, durationMins: 120, tags: ["family", "kids", "free", "outdoor", "wheelchair"] },
  { city: "JED", category: "museum", nameAr: "بيت نصيف", nameEn: "Nasseef House", descriptionAr: "من أشهر بيوت جدة التاريخية، استقبل الملك عبدالعزيز، ويضم معرضًا.", descriptionEn: "One of historic Jeddah's most famous houses, once hosting King Abdulaziz, now an exhibition.", lat: 21.4833, lng: 39.1871, hours: friAfternoon("09:00", "22:00"), durationMins: 45, tags: ["family", "indoor"] },
  { city: "JED", category: "museum", nameAr: "متحف مدينة الطيبات العالمية", nameEn: "Tayebat International City Museum", descriptionAr: "مبنى بطراز حجازي يضم مقتنيات عن تاريخ الجزيرة العربية والحضارات الإسلامية.", descriptionEn: "Hejazi-style complex with collections on Arabian and Islamic history.", lat: 21.5566, lng: 39.1872, hours: [{ days: [0, 1, 2, 3, 4, 6], open: "09:00", close: "21:00" }], durationMins: 90, tags: ["family", "indoor"] },
  { city: "JED", category: "entertainment", nameAr: "مدينة الشلال الترفيهية", nameEn: "Al Shallal Theme Park", descriptionAr: "مدينة ألعاب على الكورنيش بعجلة دوّارة وألعاب للأطفال وتزلج على الجليد.", descriptionEn: "Corniche theme park with a Ferris wheel, kids' rides and an ice rink.", lat: 21.516, lng: 39.1415, hours: daily("16:00", "00:00"), durationMins: 150, tags: ["family", "kids", "nightlife"] },
  { city: "JED", category: "entertainment", nameAr: "فقيه أكواريوم", nameEn: "Fakieh Aquarium", descriptionAr: "حوض أحياء مائية يعرض كائنات البحر الأحمر مع عروض الدلافين.", descriptionEn: "Aquarium of Red Sea marine life with dolphin shows.", lat: 21.5496, lng: 39.11, hours: daily("10:00", "22:00"), durationMins: 90, tags: ["family", "kids", "indoor", "wheelchair"] },
  { city: "JED", category: "beach", nameAr: "شاطئ أبحر", nameEn: "Obhur Beach", descriptionAr: "خليج شمال جدة للسباحة والغوص والرحلات البحرية.", descriptionEn: "Bay north of Jeddah for swimming, snorkelling and boat trips.", lat: 21.72, lng: 39.1, open24h: true, durationMins: 180, tags: ["family", "outdoor"] },
  { city: "JED", category: "shopping", nameAr: "مول العرب", nameEn: "Mall of Arabia", descriptionAr: "من أكبر مراكز التسوق في جدة بمطاعم ومنطقة ألعاب.", descriptionEn: "One of Jeddah's biggest malls with dining and a play area.", lat: 21.632, lng: 39.156, hours: daily("10:00", "00:00"), durationMins: 120, tags: ["family", "kids", "indoor", "wheelchair"] },
  { city: "JED", category: "shopping", nameAr: "سوق العلوي", nameEn: "Souq Al Alawi", descriptionAr: "سوق شعبي في جدة التاريخية للبهارات والعطور والمنسوجات.", descriptionEn: "Traditional souq in historic Jeddah for spices, perfumes and textiles.", lat: 21.4855, lng: 39.186, hours: daily("16:00", "00:00"), durationMins: 60, tags: ["family", "outdoor"] },
  { city: "JED", category: "landmark", nameAr: "متحف المجسمات المفتوح", nameEn: "Jeddah Open-Air Sculpture Museum", descriptionAr: "مجسمات فنية لفنانين عالميين على امتداد الكورنيش.", descriptionEn: "Sculptures by international artists along the corniche.", lat: 21.572, lng: 39.111, open24h: true, durationMins: 45, tags: ["family", "free", "outdoor", "wheelchair"] },
  { city: "JED", category: "landmark", nameAr: "نادي جدة لليخوت", nameEn: "Jeddah Yacht Club", descriptionAr: "مرسى يخوت بمطاعم ومقاهٍ وإطلالة على البحر مساءً.", descriptionEn: "Marina with restaurants, cafés and sea views in the evening.", lat: 21.615, lng: 39.106, hours: daily("16:00", "01:00"), durationMins: 90, tags: ["family", "outdoor", "nightlife"] },
  { city: "JED", category: "beach", nameAr: "شاطئ سيلفر ساندز", nameEn: "Silver Sands Beach", descriptionAr: "شاطئ رملي بمياه صافية ومرافق للسباحة والرياضات المائية.", descriptionEn: "Sandy beach with clear water, swimming and water-sport facilities.", lat: 21.765, lng: 39.098, hours: daily("09:00", "00:00"), durationMins: 180, tags: ["family", "outdoor"] },
  { city: "JED", category: "restaurant", nameAr: "البيك — التحلية", nameEn: "Al Baik — Tahlia", descriptionAr: "سلسلة الوجبات السريعة الأشهر في الحجاز، دجاج مقرمش بأسعار في المتناول.", descriptionEn: "The Hejaz's most famous fast-food chain: crispy chicken at low prices.", lat: 21.548, lng: 39.162, hours: daily("11:00", "02:00"), priceLevel: 1, cuisineAr: "وجبات سريعة", cuisineEn: "Fast food", durationMins: 45, tags: ["family", "kids"] },
  { city: "JED", category: "cafe", nameAr: "مقاهي البلد التاريخية", nameEn: "Al-Balad Heritage Cafés", descriptionAr: "جلسات تراثية وقهوة حجازية بين بيوت جدة التاريخية.", descriptionEn: "Heritage seating and Hejazi coffee among historic Jeddah's houses.", lat: 21.4845, lng: 39.1875, hours: daily("16:00", "01:00"), priceLevel: 1, cuisineAr: "قهوة", cuisineEn: "Coffee", durationMins: 60, tags: ["family", "outdoor"] },

  // ---------------------------------------------------------------- AlUla
  { city: "ULH", category: "heritage", nameAr: "جبل عكمة", nameEn: "Jabal Ikmah", descriptionAr: "مكتبة مفتوحة من النقوش الدادانية واللحيانية على واجهات الصخور.", descriptionEn: "An open-air library of Dadanitic and Lihyanite inscriptions on the rock faces.", lat: 26.6862, lng: 37.929, hours: daily("08:00", "18:00"), durationMins: 75, tags: ["outdoor"] },
  { city: "ULH", category: "nature", nameAr: "إطلالة حرة العويرض", nameEn: "Harrat Viewpoint", descriptionAr: "إطلالة من أعلى الهضبة البركانية على وادي العُلا عند الغروب.", descriptionEn: "Lookout from the volcanic plateau over the AlUla valley at sunset.", lat: 26.575, lng: 37.965, hours: daily("15:00", "22:00"), durationMins: 75, tags: ["family", "outdoor"] },
  { city: "ULH", category: "nature", nameAr: "مسار واحة الديموما", nameEn: "Daimumah Oasis Trail", descriptionAr: "مسار مشي بين بساتين النخيل والحمضيات في واحة العُلا.", descriptionEn: "Walking trail through the palm and citrus groves of the AlUla oasis.", lat: 26.625, lng: 37.918, open24h: true, durationMins: 90, tags: ["family", "outdoor", "free"] },
  { city: "ULH", category: "shopping", nameAr: "حي الجديدة للفنون", nameEn: "AlJadidah Arts District", descriptionAr: "حي للفنون والمعارض والمتاجر الحرفية والمقاهي بجوار البلدة القديمة.", descriptionEn: "Arts district of galleries, craft shops and cafés next to the old town.", lat: 26.619, lng: 37.92, hours: daily("16:00", "23:00"), durationMins: 75, tags: ["family", "outdoor"] },
  { city: "ULH", category: "nature", nameAr: "محمية شرعان", nameEn: "Sharaan Nature Reserve", descriptionAr: "محمية طبيعية بأودية وجبال رملية ومسارات لرؤية الحياة البرية.", descriptionEn: "Nature reserve of canyons and sandstone mountains with wildlife trails.", lat: 26.43, lng: 37.97, hours: daily("08:00", "18:00"), durationMins: 180, tags: ["outdoor"] },
  { city: "ULH", category: "nature", nameAr: "وادي عشار", nameEn: "Ashar Valley", descriptionAr: "وادٍ صحراوي بين الصخور الشاهقة للنزهات والتجارب الفاخرة.", descriptionEn: "Desert valley between towering rocks for walks and upscale experiences.", lat: 26.55, lng: 37.885, open24h: true, durationMins: 120, tags: ["family", "outdoor"] },

  // ---------------------------------------------------------------- Madinah
  { city: "MED", category: "mosque", nameAr: "مسجد القبلتين", nameEn: "Masjid Al-Qiblatain", descriptionAr: "المسجد الذي تحوّلت فيه القبلة من بيت المقدس إلى الكعبة.", descriptionEn: "The mosque where the qibla changed from Jerusalem to the Kaaba.", lat: 24.4838, lng: 39.5791, open24h: true, durationMins: 40, tags: ["free", "womenSection", "wheelchair"] },
  { city: "MED", category: "heritage", nameAr: "المساجد السبعة", nameEn: "The Seven Mosques", descriptionAr: "مساجد صغيرة في موقع غزوة الخندق.", descriptionEn: "Small mosques at the site of the Battle of the Trench.", lat: 24.4777, lng: 39.593, open24h: true, durationMins: 45, tags: ["free"] },
  { city: "MED", category: "museum", nameAr: "متحف دار المدينة", nameEn: "Dar Al Madinah Museum", descriptionAr: "متحف لتاريخ المدينة المنورة وعمارتها بمجسمات ومقتنيات نادرة.", descriptionEn: "Museum of Madinah's history and architecture with models and rare items.", lat: 24.446, lng: 39.6165, hours: friAfternoon("09:00", "20:00"), durationMins: 75, tags: ["family", "indoor", "wheelchair"] },
  { city: "MED", category: "museum", nameAr: "متحف سكة حديد الحجاز", nameEn: "Hejaz Railway Museum", descriptionAr: "محطة سكة حديد الحجاز التاريخية وقاطراتها ومعرض عن الخط.", descriptionEn: "The historic Hejaz Railway station, its locomotives and an exhibition.", lat: 24.4636, lng: 39.601, hours: friAfternoon("08:00", "18:00"), durationMins: 60, tags: ["family", "indoor", "outdoor"] },
  { city: "MED", category: "museum", nameAr: "المعرض الدولي للسيرة النبوية", nameEn: "International Museum of the Prophet's Biography", descriptionAr: "معرض تفاعلي عن السيرة النبوية والحضارة الإسلامية قرب المسجد النبوي.", descriptionEn: "Interactive museum on the Prophet's biography and Islamic civilisation near the Prophet's Mosque.", lat: 24.4705, lng: 39.609, hours: daily("09:00", "22:00"), durationMins: 90, tags: ["family", "indoor", "wheelchair"] },
  { city: "MED", category: "mosque", nameAr: "مسجد الغمامة", nameEn: "Al-Ghamamah Mosque", descriptionAr: "مسجد تاريخي قرب المسجد النبوي صلّى فيه النبي ﷺ صلاة العيد.", descriptionEn: "Historic mosque near the Prophet's Mosque where the Eid prayer was held.", lat: 24.466, lng: 39.6086, open24h: true, durationMins: 20, tags: ["free"] },
  { city: "MED", category: "park", nameAr: "ممشى قباء", nameEn: "Quba Walkway", descriptionAr: "طريق مشاة يصل بين المسجد النبوي ومسجد قباء بمقاهٍ ومساحات جلوس.", descriptionEn: "Pedestrian route between the Prophet's Mosque and Quba Mosque with cafés and seating.", lat: 24.452, lng: 39.613, open24h: true, durationMins: 60, tags: ["family", "outdoor", "free", "wheelchair"] },
  { city: "MED", category: "shopping", nameAr: "سوق التمور بالمدينة", nameEn: "Madinah Date Market", descriptionAr: "سوق لتمور المدينة الشهيرة مثل العجوة والصفاوي.", descriptionEn: "Market for Madinah's famous dates such as Ajwa and Safawi.", lat: 24.4712, lng: 39.6045, hours: friAfternoon("07:00", "23:00"), durationMins: 45, tags: ["family", "outdoor"] },
  { city: "MED", category: "shopping", nameAr: "النور مول", nameEn: "Al Noor Mall", descriptionAr: "أكبر مراكز التسوق في المدينة المنورة.", descriptionEn: "Madinah's largest shopping mall.", lat: 24.494, lng: 39.634, hours: daily("10:00", "00:00"), durationMins: 90, tags: ["family", "kids", "indoor", "wheelchair"] },

  // ---------------------------------------------------------------- Abha
  { city: "AHB", category: "heritage", nameAr: "قرية المفتاحة", nameEn: "Al Muftaha Village", descriptionAr: "قرية تراثية عسيرية تحولت إلى حي للفنون والمراسم.", descriptionEn: "Asiri heritage village turned into an arts quarter with studios.", lat: 18.221, lng: 42.506, hours: daily("16:00", "23:00"), durationMins: 60, tags: ["family", "outdoor"] },
  { city: "AHB", category: "landmark", nameAr: "الجبل الأخضر", nameEn: "Green Mountain", descriptionAr: "قمة تطل على أبها مضاءة بالأخضر ليلًا ويُصعد إليها بالتلفريك.", descriptionEn: "Peak overlooking Abha, lit green at night, reached by cable car.", lat: 18.223, lng: 42.509, hours: daily("16:00", "01:00"), durationMins: 75, tags: ["family", "kids", "outdoor", "nightlife"] },
  { city: "AHB", category: "nature", nameAr: "سد أبها", nameEn: "Abha Dam Lake", descriptionAr: "بحيرة بين الجبال بممشى ومساحات للنزهات.", descriptionEn: "Lake among the mountains with a promenade and picnic areas.", lat: 18.202, lng: 42.495, open24h: true, durationMins: 60, tags: ["family", "outdoor", "free"] },
  { city: "AHB", category: "museum", nameAr: "قصر شدا", nameEn: "Shada Palace", descriptionAr: "قصر حجري تاريخي يضم متحفًا للتراث العسيري.", descriptionEn: "Historic stone palace housing a museum of Asiri heritage.", lat: 18.217, lng: 42.504, hours: friAfternoon("08:00", "20:00"), durationMins: 45, tags: ["family", "indoor"] },
  { city: "AHB", category: "nature", nameAr: "قرية الحبلة المعلّقة", nameEn: "Al Habala Hanging Village", descriptionAr: "قرية على حافة منحدر شاهق يُنزل إليها بالتلفريك.", descriptionEn: "Village on the edge of a sheer cliff, reached by cable car.", lat: 18.0333, lng: 42.859, hours: daily("09:00", "20:00"), durationMins: 150, tags: ["family", "outdoor"] },
  { city: "AHB", category: "park", nameAr: "منتزه عسير الوطني", nameEn: "Asir National Park", descriptionAr: "غابات عرعر ومناطق تخييم ومسارات بين الجبال.", descriptionEn: "Juniper forests, camping areas and trails in the mountains.", lat: 18.25, lng: 42.4, open24h: true, durationMins: 180, tags: ["family", "outdoor", "free"] },
  { city: "AHB", category: "shopping", nameAr: "شارع الفن بأبها", nameEn: "Abha Art Street", descriptionAr: "شارع للمشاة بمحلات حرفية ومقاهٍ وعروض فنية مساءً.", descriptionEn: "Pedestrian street of craft shops, cafés and evening performances.", lat: 18.2195, lng: 42.508, hours: daily("16:00", "00:00"), durationMins: 75, tags: ["family", "outdoor"] },

  // ---------------------------------------------------------------- Eastern Province
  { city: "DMM", category: "park", nameAr: "حديقة الملك فهد بالدمام", nameEn: "King Fahd Park, Dammam", descriptionAr: "من أكبر الحدائق في المنطقة ببحيرة وألعاب ومسارات.", descriptionEn: "One of the region's largest parks with a lake, rides and paths.", lat: 26.402, lng: 50.088, hours: daily("16:00", "00:00"), durationMins: 90, tags: ["family", "kids", "outdoor"] },
  { city: "DMM", category: "beach", nameAr: "كورنيش الدمام", nameEn: "Dammam Corniche", descriptionAr: "واجهة بحرية بممشى طويل وجلسات ومطاعم.", descriptionEn: "Seafront with a long promenade, seating and restaurants.", lat: 26.4475, lng: 50.127, open24h: true, durationMins: 90, tags: ["family", "kids", "free", "outdoor", "wheelchair"] },
  { city: "DMM", category: "landmark", nameAr: "برج الماء بالخبر", nameEn: "Al Khobar Water Tower", descriptionAr: "برج بإطلالة على الخليج العربي ومطاعم ومنطقة ألعاب مائية حوله.", descriptionEn: "Tower overlooking the Arabian Gulf with restaurants and water play around it.", lat: 26.301, lng: 50.223, hours: daily("16:00", "00:00"), durationMins: 60, tags: ["family", "kids", "outdoor"] },
  { city: "DMM", category: "museum", nameAr: "مركز سايتك", nameEn: "Scitech Center", descriptionAr: "مركز علوم وتقنية تفاعلي مع قبة فلكية، مناسب للأطفال.", descriptionEn: "Interactive science and technology centre with a planetarium, great for children.", lat: 26.3095, lng: 50.221, hours: friAfternoon("09:00", "21:00"), durationMins: 120, tags: ["family", "kids", "indoor", "wheelchair"] },
  { city: "DMM", category: "heritage", nameAr: "قلعة تاروت", nameEn: "Tarout Castle", descriptionAr: "قلعة قديمة على جزيرة تاروت من أقدم المواقع المأهولة في الخليج.", descriptionEn: "Old castle on Tarout Island, one of the Gulf's oldest inhabited sites.", lat: 26.572, lng: 50.064, hours: daily("08:00", "18:00"), durationMins: 60, tags: ["family", "outdoor"] },
  { city: "DMM", category: "shopping", nameAr: "الراشد مول", nameEn: "Al Rashid Mall", descriptionAr: "مركز تسوق كبير في الخبر بمطاعم وسينما.", descriptionEn: "Large mall in Al Khobar with dining and a cinema.", lat: 26.3, lng: 50.205, hours: daily("10:00", "00:00"), durationMins: 90, tags: ["family", "kids", "indoor", "wheelchair"] },
  { city: "DMM", category: "restaurant", nameAr: "القرية التراثية بالدمام", nameEn: "Heritage Village Restaurant, Dammam", descriptionAr: "مطعم بطراز بيوت الخليج القديمة يقدم المأكولات الشعبية والبحرية.", descriptionEn: "Restaurant in old Gulf house style serving traditional and seafood dishes.", lat: 26.457, lng: 50.111, hours: daily("12:00", "00:00"), priceLevel: 2, cuisineAr: "خليجي", cuisineEn: "Gulf", durationMins: 90, tags: ["family", "seafood", "womenSection"] },

  // ---------------------------------------------------------------- Taif
  { city: "TIF", category: "nature", nameAr: "الهدا وتلفريك الطائف", nameEn: "Al Hada & Taif Cable Car", descriptionAr: "تلفريك يهبط من مرتفعات الهدا بإطلالات على طريق الجبال.", descriptionEn: "Cable car down from the Al Hada heights with views over the mountain road.", lat: 21.362, lng: 40.28, hours: daily("10:00", "22:00"), durationMins: 120, tags: ["family", "kids", "outdoor"] },
  { city: "TIF", category: "park", nameAr: "منتزه الردف", nameEn: "Al Rudaf Park", descriptionAr: "منتزه بصخور جرانيتية ضخمة ومساحات خضراء.", descriptionEn: "Park with giant granite boulders and green spaces.", lat: 21.24, lng: 40.423, hours: daily("16:00", "00:00"), durationMins: 75, tags: ["family", "kids", "outdoor", "free"] },
  { city: "TIF", category: "shopping", nameAr: "سوق البلد بالطائف", nameEn: "Taif Old Souq", descriptionAr: "سوق شعبي للعسل والورد والفواكه الموسمية والحرف.", descriptionEn: "Traditional market for honey, roses, seasonal fruit and crafts.", lat: 21.27, lng: 40.415, hours: friAfternoon("09:00", "23:00"), durationMins: 60, tags: ["family", "outdoor"] },
  { city: "TIF", category: "heritage", nameAr: "قرية الورد — مصنع ورد الطائف", nameEn: "Taif Rose Distillery Village", descriptionAr: "مزارع ومعامل تقطير الورد الطائفي، وموسمها في الربيع.", descriptionEn: "Farms and distilleries of the Taif rose; the season is in spring.", lat: 21.155, lng: 40.36, hours: daily("08:00", "18:00"), durationMins: 90, tags: ["family", "outdoor"] },

  // ---------------------------------------------------------------- Al-Ahsa
  { city: "HOF", category: "nature", nameAr: "واحة الأحساء", nameEn: "Al-Ahsa Oasis", descriptionAr: "أكبر واحة نخيل في العالم ومسجلة في التراث العالمي.", descriptionEn: "The world's largest palm oasis, a UNESCO World Heritage Site.", lat: 25.4, lng: 49.6, open24h: true, durationMins: 120, tags: ["family", "outdoor", "free"] },
  { city: "HOF", category: "heritage", nameAr: "قصر إبراهيم", nameEn: "Ibrahim Palace", descriptionAr: "قصر وقلعة تاريخية بقبة ومسجد في وسط الهفوف.", descriptionEn: "Historic palace and fort with a domed mosque in central Hofuf.", lat: 25.379, lng: 49.589, hours: friAfternoon("08:00", "20:00"), durationMins: 60, tags: ["family", "outdoor", "free"] },
  { city: "HOF", category: "mosque", nameAr: "مسجد جواثا", nameEn: "Jawatha Mosque", descriptionAr: "موقع ثاني مسجد صُلّيت فيه الجمعة في الإسلام.", descriptionEn: "Site of the second mosque where the Friday prayer was held in Islam.", lat: 25.466, lng: 49.669, open24h: true, durationMins: 30, tags: ["free"] },
  { city: "HOF", category: "nature", nameAr: "بحيرة الأصفر", nameEn: "Al Asfar Lake", descriptionAr: "بحيرة بين الكثبان الرملية تقصدها الطيور المهاجرة شتاءً.", descriptionEn: "Lake among the dunes visited by migrating birds in winter.", lat: 25.53, lng: 49.8, open24h: true, durationMins: 120, tags: ["outdoor", "free"] },

  // ---------------------------------------------------------------- Tabuk
  { city: "TUU", category: "museum", nameAr: "محطة سكة حديد الحجاز بتبوك", nameEn: "Tabuk Hejaz Railway Station", descriptionAr: "محطة تاريخية مرممة بمعرض عن سكة حديد الحجاز.", descriptionEn: "Restored historic station with an exhibition on the Hejaz Railway.", lat: 28.393, lng: 36.569, hours: friAfternoon("08:00", "18:00"), durationMins: 45, tags: ["family", "indoor"] },
  { city: "TUU", category: "nature", nameAr: "صحراء حسمى", nameEn: "Hisma Desert", descriptionAr: "صحراء بتكوينات صخرية رملية ملونة وأقواس طبيعية.", descriptionEn: "Desert of colourful sandstone formations and natural arches.", lat: 28.75, lng: 36.2, open24h: true, durationMins: 240, tags: ["outdoor", "free"] },
  { city: "TUU", category: "shopping", nameAr: "سوق تبوك الشعبي", nameEn: "Tabuk Traditional Souq", descriptionAr: "سوق للمنتجات المحلية والتمور والحرف البدوية.", descriptionEn: "Market for local produce, dates and Bedouin crafts.", lat: 28.3835, lng: 36.566, hours: friAfternoon("09:00", "23:00"), durationMins: 60, tags: ["family", "outdoor"] },

  // ---------------------------------------------------------------- Hail
  { city: "HAS", category: "heritage", nameAr: "قلعة عيرف", nameEn: "A'arif Fort", descriptionAr: "قلعة طينية على تل تطل على مدينة حائل.", descriptionEn: "Mud-brick fort on a hill overlooking Hail.", lat: 27.513, lng: 41.693, hours: daily("08:00", "20:00"), durationMins: 45, tags: ["family", "outdoor", "free"] },
  { city: "HAS", category: "heritage", nameAr: "قصر القشلة", nameEn: "Qishlah Palace", descriptionAr: "قصر طيني كبير بفناء واسع وأبراج دفاعية.", descriptionEn: "Large mud-brick palace with a wide courtyard and defensive towers.", lat: 27.5215, lng: 41.696, hours: friAfternoon("08:00", "20:00"), durationMins: 45, tags: ["family", "outdoor", "free"] },
  { city: "HAS", category: "nature", nameAr: "جبال أجا", nameEn: "Aja Mountains", descriptionAr: "سلسلة جبلية بتكوينات صخرية وأودية ونقوش.", descriptionEn: "Mountain range of rock formations, valleys and inscriptions.", lat: 27.55, lng: 41.45, open24h: true, durationMins: 180, tags: ["outdoor", "free"] },

  // ---------------------------------------------------------------- Yanbu
  { city: "YNB", category: "beach", nameAr: "كورنيش ينبع", nameEn: "Yanbu Corniche", descriptionAr: "واجهة بحرية بممشى وجلسات على البحر الأحمر.", descriptionEn: "Red Sea waterfront with a promenade and seating.", lat: 24.089, lng: 38.06, open24h: true, durationMins: 90, tags: ["family", "kids", "free", "outdoor"] },
  { city: "YNB", category: "heritage", nameAr: "ينبع التاريخية", nameEn: "Historic Yanbu", descriptionAr: "بيوت مرجانية ورواشين في المنطقة التاريخية القديمة.", descriptionEn: "Coral-stone houses and rawashin in the old historic quarter.", lat: 24.09, lng: 38.058, open24h: true, durationMins: 75, tags: ["family", "outdoor", "free"] },
  { city: "YNB", category: "beach", nameAr: "شرم ينبع", nameEn: "Sharm Yanbu", descriptionAr: "خليج للغوص والسباحة بين الشعاب المرجانية.", descriptionEn: "Bay for diving and swimming among the coral reefs.", lat: 24.18, lng: 37.99, open24h: true, durationMins: 180, tags: ["outdoor"] },
];
