/**
 * Curated starter content of the guide (major landmarks per city), loaded once into the database
 * and then managed by the operations team from the back office. Coordinates are approximate and
 * should be reviewed before launch.
 */
import type { OpeningSlot, Place } from "./types";

export { CITY_CENTERS } from "./centers";

const daily = (open: string, close: string): OpeningSlot[] => [{ days: [0, 1, 2, 3, 4, 5, 6], open, close }];
type Seed = Omit<Place, "id" | "source" | "status" | "updatedAt" | "tags"> & { tags?: Place["tags"] };

const SEED: Seed[] = [
  // Riyadh
  { city: "RUH", category: "heritage", nameAr: "حي الطريف التاريخي — الدرعية", nameEn: "At-Turaif District, Diriyah", descriptionAr: "موقع مسجل في التراث العالمي لليونسكو، وعاصمة الدولة السعودية الأولى بمبانيها الطينية النجدية.", descriptionEn: "UNESCO World Heritage Site and capital of the first Saudi state, with its Najdi mud-brick architecture.", lat: 24.7336, lng: 46.5753, hours: daily("16:00", "00:00"), durationMins: 150, tags: ["family", "outdoor"] },
  { city: "RUH", category: "restaurant", nameAr: "مطل البجيري", nameEn: "Bujairi Terrace", descriptionAr: "وجهة مطاعم ومقاهٍ عالمية ومحلية تطل على حي الطريف في الدرعية.", descriptionEn: "Dining destination of international and local restaurants overlooking At-Turaif in Diriyah.", lat: 24.7353, lng: 46.577, hours: daily("16:00", "01:00"), priceLevel: 3, cuisineAr: "متنوع", cuisineEn: "Various", durationMins: 90, tags: ["family", "outdoor", "vegetarian"] },
  { city: "RUH", category: "heritage", nameAr: "قصر المصمك", nameEn: "Masmak Fortress", descriptionAr: "حصن طيني تاريخي ارتبط بتأسيس المملكة، ويضم متحفًا عن تاريخ الرياض.", descriptionEn: "Historic clay fortress linked to the founding of the Kingdom, housing a museum on Riyadh's history.", lat: 24.6312, lng: 46.7134, hours: [{ days: [0, 1, 2, 3, 4, 6], open: "08:00", close: "21:00" }, { days: [5], open: "16:00", close: "21:00" }], durationMins: 60, tags: ["family", "free", "indoor"] },
  { city: "RUH", category: "museum", nameAr: "المتحف الوطني السعودي", nameEn: "National Museum of Saudi Arabia", descriptionAr: "رحلة عبر تاريخ الجزيرة العربية من عصور ما قبل التاريخ حتى توحيد المملكة.", descriptionEn: "A journey through the history of the Arabian Peninsula from prehistory to the unification of the Kingdom.", lat: 24.6477, lng: 46.7101, hours: [{ days: [0, 1, 2, 3, 4, 6], open: "09:00", close: "20:00" }, { days: [5], open: "16:00", close: "20:00" }], durationMins: 120, tags: ["family", "kids", "wheelchair", "indoor"] },
  { city: "RUH", category: "landmark", nameAr: "جسر المملكة — برج المملكة", nameEn: "Kingdom Centre Sky Bridge", descriptionAr: "جسر زجاجي في أعلى برج المملكة بإطلالة بانورامية على الرياض.", descriptionEn: "Glass bridge at the top of Kingdom Centre with panoramic views over Riyadh.", lat: 24.7114, lng: 46.6744, hours: daily("09:30", "23:00"), durationMins: 45, tags: ["family", "wheelchair", "indoor"] },
  { city: "RUH", category: "nature", nameAr: "حافة العالم", nameEn: "Edge of the World", descriptionAr: "منحدرات جبال طويق الشاهقة، ويُنصح بزيارتها مع مرشد وسيارة دفع رباعي.", descriptionEn: "Dramatic cliffs of the Tuwaiq escarpment; best visited with a guide and a 4x4.", lat: 24.9538, lng: 45.9917, open24h: true, durationMins: 240, tags: ["outdoor", "free"] },
  { city: "RUH", category: "entertainment", nameAr: "بوليفارد رياض سيتي", nameEn: "Boulevard Riyadh City", descriptionAr: "منطقة ترفيهية بمطاعم وعروض وفعاليات، ومن أبرز مناطق موسم الرياض.", descriptionEn: "Entertainment district with restaurants, shows and events, a highlight of Riyadh Season.", lat: 24.7686, lng: 46.6013, hours: daily("16:00", "02:00"), durationMins: 180, tags: ["family", "kids", "nightlife", "outdoor"] },
  // Jeddah
  { city: "JED", category: "heritage", nameAr: "جدة التاريخية (البلد)", nameEn: "Historic Jeddah (Al-Balad)", descriptionAr: "موقع تراث عالمي ببيوته المرجانية ورواشينه الخشبية وأسواقه القديمة.", descriptionEn: "UNESCO World Heritage Site with coral-stone houses, wooden rawashin and old souqs.", lat: 21.4858, lng: 39.1868, open24h: true, durationMins: 150, tags: ["family", "free", "outdoor"] },
  { city: "JED", category: "landmark", nameAr: "نافورة الملك فهد", nameEn: "King Fahd's Fountain", descriptionAr: "من أعلى النوافير في العالم، وتُشاهد من الكورنيش مساءً.", descriptionEn: "One of the tallest fountains in the world, best seen from the corniche in the evening.", lat: 21.515, lng: 39.145, open24h: true, durationMins: 30, tags: ["family", "free", "outdoor"] },
  { city: "JED", category: "beach", nameAr: "كورنيش جدة", nameEn: "Jeddah Corniche", descriptionAr: "واجهة بحرية ممتدة على البحر الأحمر بممشى ومجسمات فنية وأماكن للجلوس.", descriptionEn: "Red Sea waterfront with promenades, public art and seating areas.", lat: 21.57, lng: 39.11, open24h: true, durationMins: 90, tags: ["family", "kids", "free", "outdoor", "wheelchair"] },
  { city: "JED", category: "mosque", nameAr: "مسجد الرحمة (المسجد العائم)", nameEn: "Al-Rahma Mosque (Floating Mosque)", descriptionAr: "مسجد مبني على البحر يبدو عائمًا عند المد.", descriptionEn: "Mosque built over the sea that appears to float at high tide.", lat: 21.543, lng: 39.105, open24h: true, durationMins: 30, tags: ["free"] },
  { city: "JED", category: "shopping", nameAr: "رد سي مول", nameEn: "Red Sea Mall", descriptionAr: "من أكبر مراكز التسوق في جدة بعلامات تجارية ومطاعم وترفيه.", descriptionEn: "One of Jeddah's largest malls with brands, dining and entertainment.", lat: 21.6268, lng: 39.1106, hours: daily("10:00", "00:00"), durationMins: 120, tags: ["family", "kids", "wheelchair", "indoor"] },
  // AlUla
  { city: "ULH", category: "heritage", nameAr: "الحِجر (مدائن صالح)", nameEn: "Hegra", descriptionAr: "أول موقع سعودي في قائمة التراث العالمي، بمقابره النبطية المنحوتة في الصخر. الدخول بتذكرة وجولة.", descriptionEn: "Saudi Arabia's first UNESCO site, with rock-cut Nabataean tombs. Entry with a ticketed tour.", lat: 26.7917, lng: 37.9533, hours: daily("08:00", "18:00"), durationMins: 180, tags: ["family", "outdoor"] },
  { city: "ULH", category: "nature", nameAr: "جبل الفيل", nameEn: "Elephant Rock", descriptionAr: "تكوين صخري طبيعي على شكل فيل، وجهة مسائية بجلسات ومقهى.", descriptionEn: "Natural rock formation shaped like an elephant; an evening spot with seating and a café.", lat: 26.6563, lng: 37.8538, hours: daily("16:00", "23:00"), durationMins: 60, tags: ["family", "free", "outdoor"] },
  { city: "ULH", category: "heritage", nameAr: "البلدة القديمة بالعُلا", nameEn: "AlUla Old Town", descriptionAr: "بلدة طينية تاريخية بأزقتها ومحلاتها الحرفية.", descriptionEn: "Historic mud-brick town with alleys and craft shops.", lat: 26.618, lng: 37.9165, hours: daily("09:00", "23:00"), durationMins: 90, tags: ["family", "free", "outdoor"] },
  { city: "ULH", category: "landmark", nameAr: "مرايا", nameEn: "Maraya", descriptionAr: "أكبر مبنى مغطى بالمرايا في العالم، قاعة للحفلات والفعاليات.", descriptionEn: "The world's largest mirrored building, a concert and events venue.", lat: 26.6392, lng: 37.887, durationMins: 45, tags: ["family", "outdoor"] },
  { city: "ULH", category: "heritage", nameAr: "دادان", nameEn: "Dadan", descriptionAr: "عاصمة مملكتي دادان ولحيان القديمتين، بنقوشها ومقابر الأسود.", descriptionEn: "Ancient capital of the Dadan and Lihyan kingdoms, with inscriptions and the Lion Tombs.", lat: 26.6455, lng: 37.9337, hours: daily("08:00", "18:00"), durationMins: 90, tags: ["outdoor"] },
  // Madinah
  { city: "MED", category: "mosque", nameAr: "المسجد النبوي", nameEn: "The Prophet's Mosque", descriptionAr: "ثاني أقدس المساجد في الإسلام، ويضم الروضة الشريفة.", descriptionEn: "The second holiest mosque in Islam, home to Al-Rawdah.", lat: 24.4672, lng: 39.6112, open24h: true, durationMins: 120, tags: ["free", "wheelchair", "womenSection"] },
  { city: "MED", category: "mosque", nameAr: "مسجد قباء", nameEn: "Quba Mosque", descriptionAr: "أول مسجد بُني في الإسلام.", descriptionEn: "The first mosque built in Islam.", lat: 24.4393, lng: 39.6173, open24h: true, durationMins: 45, tags: ["free", "womenSection"] },
  { city: "MED", category: "heritage", nameAr: "جبل أحد", nameEn: "Mount Uhud", descriptionAr: "موقع غزوة أحد ومقبرة شهدائها.", descriptionEn: "Site of the Battle of Uhud and its martyrs' cemetery.", lat: 24.504, lng: 39.613, open24h: true, durationMins: 60, tags: ["free", "outdoor"] },
  // Abha
  { city: "AHB", category: "nature", nameAr: "السودة", nameEn: "Al Soudah", descriptionAr: "أعلى قمم المملكة بغابات العرعر والضباب وأجواء معتدلة صيفًا.", descriptionEn: "The Kingdom's highest peaks with juniper forests, mist and mild summers.", lat: 18.27, lng: 42.37, open24h: true, durationMins: 180, tags: ["family", "outdoor", "free"] },
  { city: "AHB", category: "heritage", nameAr: "قرية رجال ألمع التراثية", nameEn: "Rijal Almaa Heritage Village", descriptionAr: "قرية حجرية ملونة على سفح الجبل ومتحف للتراث العسيري.", descriptionEn: "Colourful stone village on a mountainside with an Asiri heritage museum.", lat: 18.215, lng: 42.269, hours: daily("08:00", "22:00"), durationMins: 120, tags: ["family", "outdoor"] },
  // Eastern Province
  { city: "DMM", category: "museum", nameAr: "إثراء — مركز الملك عبدالعزيز الثقافي العالمي", nameEn: "Ithra — King Abdulaziz Center for World Culture", descriptionAr: "مركز ثقافي بمتحف ومكتبة ومسرح وسينما ومعارض.", descriptionEn: "Cultural centre with a museum, library, theatre, cinema and exhibitions.", lat: 26.3328, lng: 50.1177, hours: [{ days: [0, 1, 2, 3, 4, 5, 6], open: "09:00", close: "23:00" }], durationMins: 180, tags: ["family", "kids", "wheelchair", "indoor"] },
  { city: "DMM", category: "beach", nameAr: "كورنيش الخبر", nameEn: "Al Khobar Corniche", descriptionAr: "واجهة بحرية على الخليج العربي بممشى وحدائق ومطاعم.", descriptionEn: "Arabian Gulf waterfront with a promenade, gardens and restaurants.", lat: 26.295, lng: 50.22, open24h: true, durationMins: 90, tags: ["family", "kids", "free", "outdoor", "wheelchair"] },
  { city: "DMM", category: "beach", nameAr: "شاطئ نصف القمر", nameEn: "Half Moon Bay", descriptionAr: "خليج رملي على شكل هلال للسباحة والرياضات البحرية.", descriptionEn: "Crescent-shaped bay for swimming and water sports.", lat: 26.14, lng: 50.115, open24h: true, durationMins: 180, tags: ["family", "outdoor"] },
  // Taif
  { city: "TIF", category: "nature", nameAr: "الشفا", nameEn: "Al Shafa", descriptionAr: "مرتفعات جبلية بمزارع الفواكه والورد الطائفي وأجواء باردة.", descriptionEn: "Mountain heights with fruit and Taif-rose farms and cool weather.", lat: 21.07, lng: 40.35, open24h: true, durationMins: 180, tags: ["family", "outdoor", "free"] },
  { city: "TIF", category: "museum", nameAr: "قصر شبرا", nameEn: "Shubra Palace", descriptionAr: "قصر تاريخي بطراز معماري مميز، يضم متحفًا إقليميًا.", descriptionEn: "Historic palace with distinctive architecture, housing a regional museum.", lat: 21.27, lng: 40.415, durationMins: 60, tags: ["family", "indoor"] },
  // Tabuk
  { city: "TUU", category: "nature", nameAr: "وادي الديسة", nameEn: "Wadi Disah", descriptionAr: "وادٍ بين جبال رملية شاهقة وينابيع ونخيل.", descriptionEn: "Valley between towering sandstone mountains with springs and palms.", lat: 27.63, lng: 36.48, open24h: true, durationMins: 240, tags: ["outdoor", "free"] },
  { city: "TUU", category: "heritage", nameAr: "قلعة تبوك", nameEn: "Tabuk Castle", descriptionAr: "قلعة تاريخية على طريق الحج الشامي.", descriptionEn: "Historic castle on the Levantine pilgrimage route.", lat: 28.38, lng: 36.57, durationMins: 45, tags: ["family", "free"] },
  // Al-Ahsa
  { city: "HOF", category: "nature", nameAr: "جبل القارة", nameEn: "Al Qarah Mountain", descriptionAr: "جبل بكهوف طبيعية باردة وسط واحة الأحساء المسجلة في اليونسكو.", descriptionEn: "Mountain with naturally cool caves in the UNESCO-listed Al-Ahsa oasis.", lat: 25.425, lng: 49.68, hours: daily("09:00", "22:00"), durationMins: 90, tags: ["family", "outdoor"] },
  { city: "HOF", category: "shopping", nameAr: "سوق القيصرية", nameEn: "Al Qaisariah Souq", descriptionAr: "من أقدم الأسواق الشعبية في المنطقة، للتمور والبشوت والحرف.", descriptionEn: "One of the region's oldest traditional souqs, for dates, bishts and crafts.", lat: 25.382, lng: 49.586, hours: [{ days: [0, 1, 2, 3, 4, 6], open: "09:00", close: "22:00" }, { days: [5], open: "16:00", close: "22:00" }], durationMins: 60, tags: ["family", "outdoor"] },
  // Hail
  { city: "HAS", category: "heritage", nameAr: "نقوش جبة الصخرية", nameEn: "Jubbah Rock Art", descriptionAr: "نقوش صخرية عمرها آلاف السنين مسجلة في التراث العالمي.", descriptionEn: "Rock art thousands of years old, a UNESCO World Heritage Site.", lat: 28.02, lng: 40.92, hours: daily("08:00", "17:00"), durationMins: 120, tags: ["outdoor"] },
];

const slug = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");

export function seedPlaces(now = new Date().toISOString()): Place[] {
  return SEED.map((s) => ({ tags: [], ...s, id: `cur-${s.city.toLowerCase()}-${slug(s.nameEn)}`, source: "curated" as const, status: "published" as const, updatedAt: now }));
}
